config/routes.rb
Rails.application.routes.draw do
  resources :staff_infos
  resources :histories
  resources :customers

  root 'home_index#top'

end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id               :integer          not null, primary key
#  company_name     :string
#  zip              :string
#  address          :string
#  tel              :string
#  responsible_name :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Customer < ActiveRecord::Base
  has_many :histories
  validates :company_name, :zip , :address, :tel, :responsible_name, presence: {present: true, message: "必須入力です。記入をお願いします。"}
end

app/models/history.rb
# == Schema Information
#
# Table name: histories
#
#  id                :integer          not null, primary key
#  activity_time     :datetime
#  customer_id       :integer
#  sales_category    :string
#  sales_achievement :string
#  detail            :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class History < ActiveRecord::Base
  belongs_to :customer
  belongs_to :staff_info
  validates :activity_time, :customer_id, :sales_category, :sales_achievement,presence: {present: true, message: "必須入力です。記入をお願いします。"}
  validates(:staff_info_id, :inclusion => StaffInfo.ids)

  def self.chart_h
    history_dummy = History.where(sales_achievement:"達成").group(:staff_info_id).count
    history_profit = Hash.new
    history_dummy.each do |i,val|
      history_profit[StaffInfo.find(i).name] = val
    end
    return history_profit
  end

  paginates_per 20  # 1ページあたり5項目表示
end

app/models/staff_info.rb
# == Schema Information
#
# Table name: staff_infos
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class StaffInfo < ActiveRecord::Base
  has_many :histories
  validates :name, presence: {present: true, message: "必須入力です。記入をお願いします。"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: '新規顧客情報を登録しました' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: '顧客情報を削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:company_name, :zip, :address, :tel, :responsible_name)
    end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
    #page-nationのため
    @histories = History.page(params[:page])

  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: '新規営業履歴を登録しました' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: '営業履歴を削除しました' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:activity_time, :customer_id, :sales_category, :sales_achievement, :detail ,:staff_info_id)
    end

end

app/controllers/home_index_controller.rb
class HomeIndexController < ApplicationController
end

app/controllers/staff_infos_controller.rb
class StaffInfosController < ApplicationController
  before_action :set_staff_info, only: [:show, :edit, :update, :destroy]

  # GET /staff_infos
  # GET /staff_infos.json
  def index
    @staff_infos = StaffInfo.all
  end

  # GET /staff_infos/1
  # GET /staff_infos/1.json
  def show
  end

  # GET /staff_infos/new
  def new
    @staff_info = StaffInfo.new
  end

  # GET /staff_infos/1/edit
  def edit
  end

  # POST /staff_infos
  # POST /staff_infos.json
  def create
    @staff_info = StaffInfo.new(staff_info_params)

    respond_to do |format|
      if @staff_info.save
        format.html { redirect_to @staff_info, notice: 'Staff info was successfully created.' }
        format.json { render :show, status: :created, location: @staff_info }
      else
        format.html { render :new }
        format.json { render json: @staff_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staff_infos/1
  # PATCH/PUT /staff_infos/1.json
  def update
    respond_to do |format|
      if @staff_info.update(staff_info_params)
        format.html { redirect_to @staff_info, notice: '新しい社員情報を登録しました' }
        format.json { render :show, status: :ok, location: @staff_info }
      else
        format.html { render :edit }
        format.json { render json: @staff_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staff_infos/1
  # DELETE /staff_infos/1.json
  def destroy
    @staff_info.destroy
    respond_to do |format|
      format.html { redirect_to staff_infos_url, notice: '社員情報を削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff_info
      @staff_info = StaffInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_info_params
      params.require(:staff_info).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/home_index_helper.rb
module HomeIndexHelper
end

app/helpers/staff_infos_helper.rb
module StaffInfosHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"会社名" %><br>
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :"郵便番号" %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :"住所" %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :"電話番号" %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :"担当者名" %><br>
    <%= f.text_field :responsible_name %>
  </div>
  <div class="actions">
    <%= f.submit :"登録" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h2 id="kokyakutitle2">顧客情報編集</h2>

<%= render 'form' %>

<%= link_to '内容確認', @customer %> |
<%= link_to '戻る', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h2 id="kokyakutitle">顧客リスト</h2>

<table>
  <thead>
    <tr>
      <th>顧客ID</th>
      <th>会社名</th>
      <th>郵便番号</th>
      <th>住所</th>
      <th>電話番号</th>
      <th>担当者名</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= customer.company_name %></td>
        <td><%= customer.zip %></td>
        <td><%= customer.address %></td>
        <td><%= customer.tel %></td>
        <td><%= customer.responsible_name %></td>
        <td><%= link_to '確認', customer %></td>
        <td><%= link_to '編集', edit_customer_path(customer) %></td>
        <td><%= link_to '削除', customer, method: :delete, data: { confirm: '本当に消してもよろしいですか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div id="newsave">
<%= link_to '新規登録', new_customer_path %>
</div>

app/views/customers/new.html.erb
<h2 id="kokyakutitle2">新規顧客</h2>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>会社名:</strong>
  <%= @customer.company_name %>
</p>

<p>
  <strong>郵便番号:</strong>
  <%= @customer.zip %>
</p>

<p>
  <strong>住所:</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>電話番号:</strong>
  <%= @customer.tel %>
</p>

<p>
  <strong>担当者名:</strong>
  <%= @customer.responsible_name %>
</p>

<%= link_to '編集', edit_customer_path(@customer) %> |
<%= link_to '戻る', customers_path %>

app/views/histories/_form.html.erb
<%= form_for(@history) do |f| %>
  <% if @history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% @history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"活動日時" %><br>
    <%= f.datetime_select :activity_time %>
  </div>
  <div class="field">
    <%= f.label :"会社名" %><br>
    <%= f.collection_select(:customer_id, Customer.all, :id, :company_name) %>
  </div>
  <div class="field">
    <%= f.label :"営業区分" %><br>
    <%= f.select(:sales_category, options_for_select(%w{商品案内 契約 フォロー クレーム処理 },'商品案内')) %>
  </div>
  <div class="field">
    <%= f.label :"営業成果" %><br>
    <%= f.select(:sales_achievement, options_for_select(%w{達成 継続 失敗}, '継続')) %>
  </div>
  <div class="field">
    <%= f.label :"営業担当者ID" %><br>
    <%= f.text_field :staff_info_id %>
    <%#= @history.staff_info.name %>
  <div class="field">
    <%= f.label :"詳細" %><br>
    <%= f.text_area :detail %>
  </div>
  <div class="actions">
    <%= f.submit :"登録" %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h2 id="historytitle2">新規営業履歴</h2>

<%= render 'form' %>

<%= link_to '確認', @history %> |
<%= link_to '戻る', histories_path %>

app/views/histories/index.html.erb
<p id="notice"><%= notice %></p>

<h2 id="historytitle">営業リスト</h2>






<table>
  <thead>
    <tr>
      <th>営業日時</th>
      <th>顧客名</th>
      <th>営業区分</th>
      <th>営業成果</th>
      <th>詳細</th>
      <th>営業担当者名</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.activity_time %></td>
        <td><%= history.customer.company_name %></td>
        <td><%= history.sales_category %></td>
        <td><%= history.sales_achievement %></td>
        <td><%= history.detail %></td>
        <td><%= history.staff_info.name %></td>
        <td><%= link_to '確認', history %></td>
        <td><%= link_to '編集', edit_history_path(history) %></td>
        <td><%= link_to '削除', history, method: :delete, data: { confirm: '本当に消してもよろしいですか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to '新規登録', new_history_path %>

<!-- 追加箇所開始 -->
<%= paginate @histories %>
<!-- 追加箇所終了 -->

<br>

<%= column_chart History.chart_h %>

app/views/histories/new.html.erb
<h2 id="historytitle2">新規営業履歴</h2>

<%= render 'form' %>

<%= link_to '戻る', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>活動日時:</strong>
  <%= @history.activity_time %>
</p>

<p>
  <strong>会社名:</strong>
  <%= @history.customer.company_name %>
</p>

<p>
  <strong>営業区分:</strong>
  <%= @history.sales_category %>
</p>

<p>
  <strong>営業成果:</strong>
  <%= @history.sales_achievement %>
</p>

<p>
  <strong>営業担当者名:</strong>
  <%= @history.staff_info.name %>
</p>

<p>
  <strong>詳細:</strong>
  <%= @history.detail %>
</p>

<%= link_to '編集', edit_history_path(@history) %> |
<%= link_to '戻る', histories_path %>

app/views/home_index/top.html.erb
<div id="top">

  <div class="mdl-grid">
    <div class="mdl-cell mdl-cell--4-col">
      <div class="demo-card-event mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand">
          <i class="material-icons md-48">business</i>
        </div>
        <div class="mdl-card__actions mdl-card--border">
            <span id="select_name"><%= link_to "営業リスト", histories_path %></span>
          <div class="mdl-layout-spacer"></div>
        </div>
      </div>
    </div>
    <div class="mdl-cell mdl-cell--4-col">
      <div class="demo-card-event mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand">
          <i class="material-icons md-48">list</i>
        </div>
        <div class="mdl-card__actions mdl-card--border">
            <span id="select_name"><%= link_to "顧客リスト", customers_path %></span>
          <div class="mdl-layout-spacer"></div>
        </div>
      </div>
    </div>
    <div class="mdl-cell mdl-cell--4-col">
      <div class="demo-card-event mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand">
          <i class="material-icons md-48">group</i>
        </div>
        <div class="mdl-card__actions mdl-card--border">
            <span id="select_name"><%= link_to "社員リスト", customers_path %></span>
          <div class="mdl-layout-spacer"></div>
        </div>
      </div>
    </div>
    <div class="mdl-cell mdl-cell--4-col">
      <div class="demo-card-event mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand">
          <i class="material-icons md-48">library_add</i>
        </div>
        <div class="mdl-card__actions mdl-card--border">
            <span id="select_name"><%= link_to "新規営業履歴", 'histories/new' %></span>

          <div class="mdl-layout-spacer"></div>
        </div>
      </div>
    </div>
    <div class="mdl-cell mdl-cell--4-col">
      <div class="demo-card-event mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand">
          <i class="material-icons md-48">face</i>
        </div>
        <div class="mdl-card__actions mdl-card--border">
            <span id="select_name"><%= link_to "新規顧客", 'customers/new' %></span>
          <div class="mdl-layout-spacer"></div>
        </div>
      </div>
  </div>
  <div class="mdl-cell mdl-cell--4-col">
      <div class="demo-card-event mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand">
          <i class="material-icons md-48">person_add</i>
        </div>
        <div class="mdl-card__actions mdl-card--border">
            <span id="select_name"><%= link_to "新規社員登録", customers_path %></span>
          <div class="mdl-layout-spacer"></div>
        </div>
      </div>
    </div>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SalesHistory</title>
  <script src="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.min.js"></script>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.blue_grey-indigo.min.css" />
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
</head>
<body>
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title"><%= link_to '営業管理データベース', root_path %></span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation. We hide it in small screens. -->
<!--       <nav class="mdl-navigation mdl-layout--large-screen-only">
        <a class="mdl-navigation__link" href="">Link</a>
        <a class="mdl-navigation__link" href="">Link</a>
        <a class="mdl-navigation__link" href="">Link</a>
        <a class="mdl-navigation__link" href="">Link</a>
      </nav> -->
    </div>
  </header>
  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title">リスト</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" href=" <%= root_path %> "><i class="material-icons">account_balance</i>TOP</a>
      <a class="mdl-navigation__link" href=" <%= histories_path %> "><i class="material-icons">business</i>営業リスト</a>
      <a class="mdl-navigation__link" href=" <%= customers_path %> "><i class="material-icons">account_box</i>顧客リスト</a>
      <a class="mdl-navigation__link" href=" <%=staff_infos_path %> "><i class="material-icons">group</i>社員リスト</a>
    </nav>
  </div>
  <main class="mdl-layout__content">
    <div class="page-content">
    <!-- Your content goes here -->
    <%= yield %>
    </div>
  </main>
</div>

</body>
</html>

app/views/staff_infos/_form.html.erb
<%= form_for(@staff_info) do |f| %>
  <% if @staff_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff_info.errors.count, "error") %> prohibited this staff_info from being saved:</h2>

      <ul>
      <% @staff_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"氏名" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit :"登録" %>
  </div>
<% end %>

app/views/staff_infos/edit.html.erb
<h2 id="syainmei2">社員名 編集</h2>

<%= render 'form' %>

<%= link_to 'Show', @staff_info %> |
<%= link_to 'Back', staff_infos_path %>

app/views/staff_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h2 id="syainmei">社員リスト</h2>

<table>
  <thead>
    <tr>
      <th>社員ID</th>
      <th>氏名</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staff_infos.each do |staff_info| %>
      <tr>
        <td><%= staff_info.id %></td>
        <td><%= staff_info.name %></td>
        <td><%= link_to '確認', staff_info %></td>
        <td><%= link_to '編集', edit_staff_info_path(staff_info) %></td>
        <td><%= link_to '削除', staff_info, method: :delete, data: { confirm: '本当によろしいですか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div id="newsave">
<%= link_to '新規登録', new_staff_info_path %>
</div>

app/views/staff_infos/new.html.erb
<h2 id="syainmei2">社員 登録</h2>

<%= render 'form' %>

<%= link_to '戻る', staff_infos_path %>

app/views/staff_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>氏名:</strong>
  <%= @staff_info.name %>
</p>

<%= link_to '編集', edit_staff_info_path(@staff_info) %> |
<%= link_to '戻る', staff_infos_path %>